services:
  student_service:
    build: .
    image: jvs99/student_service:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"

  mongo:
    image: mongo:4
    restart: unless-stopped
    ports:
      - "27017:27017"
